In [1]:
# 序列化通常是保存模型，读写模型，以及对参数的读写操作。

from mxnet import nd

x = nd.zeros(3)
y = nd.zeros(4)

filename = 'data/data1'
nd.save(filename, [x, y])

In [2]:
# 读取信息
a, b = nd.load(filename)
print(a, b)


[0. 0. 0.]
<NDArray 3 @cpu(0)> 
[0. 0. 0. 0.]
<NDArray 4 @cpu(0)>


In [3]:
# 读取gluon的模型和参数信息

from mxnet.gluon import nn

def get_net():
    net = nn.Sequential()
    with net.name_scope():
        net.add(nn.Dense(10, activation='relu'))
        net.add(nn.Dense(2))
    return net


net = get_net()
net.initialize()
x = nd.random.uniform(shape=(2, 10))
net(x)

datafile = 'data/net.params'
#net.save_params(datafile) 替换为下面代码
net.save_parameters(datafile)

In [10]:
import mxnet as mx

net2 = get_net()
net2.load_parameters(datafile, ctx=mx.cpu())
net2(x)


[[ 0.00202204  0.00100273]
 [-0.00134863  0.00299659]]
<NDArray 2x2 @cpu(0)>